[package]
name = "packet-analyser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = { version = "1.1.0", features = ["capture-stream"] }
byteorder = "1.5.0"
chrono = "0.4.31"